name: Romain Berger
markdown: redcarpet
exclude:
    - Rakefile
    - Makefile
    - Readme.md
    - LICENSE.md
    - Gemfile.lock
    - Gemfile
    - node_modules
    - package.json
    - npm-debug.log
    - config.rb
    - sprites
    - '*.scss'
    - tasks
permalink: pretty
